# model
model_name_or_path: [MODEL_PATH]

# method
stage: sft
do_train: true
finetuning_type: full

# ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

# dataset
dataset: [DATASET_NAME]
template: llama2
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: [OUTPUT_DIR]
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

# train 
# StructLM was trained with effective bsize = 512 = per_device_bsize * grad_acc_steps * num_gpus 
per_device_train_batch_size: [BSIZE]
gradient_accumulation_steps: [GRAD_ACC]
learning_rate: 0.00002
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 0.05
pure_bf16: true

# eval
val_size: 0.1
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500
